<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michelle Ju Young Rhee">
<meta name="dcterms.date" content="2023-03-17">
<meta name="description" content="How has the opioid overdose deaths in the U.S. progressed from 1999 to 2019 by sex and race?">

<title>opioid_blog - Evolution of Opioid Overdose Death in the US</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">opioid_blog</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Evolution of Opioid Overdose Death in the US</h1>
                  <div>
        <div class="description">
          How has the opioid overdose deaths in the U.S. progressed from 1999 to 2019 by sex and race?
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Michelle Ju Young Rhee </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 17, 2023</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">March 17, 2023</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="research-question-how-has-the-opioid-overdose-deaths-in-the-u.s.-progressed-from-1999-to-2019-by-sex-and-race" class="level3">
<h3 class="anchored" data-anchor-id="research-question-how-has-the-opioid-overdose-deaths-in-the-u.s.-progressed-from-1999-to-2019-by-sex-and-race">Research Question: <strong><em>How has the opioid overdose deaths in the U.S. progressed from 1999 to 2019 by sex and race?</em></strong></h3>
</section>
<section id="i.-introduction" class="level2">
<h2 class="anchored" data-anchor-id="i.-introduction">I. Introduction</h2>
<p><br> For my final project, I decided to analyze the evolution of the opioid overdose in the United States from 1999 to 2019 and delve deeper into comparing the opioid overdose growth rate of varying races and sex. I felt motivated to use this opioid data file after watching a documentary about opioid overdose epidemic and how it has rapidly grown over the past decade across the United States. I became interested in analyzing how opioid overdose has impacted a wide range of races and sex and creating new dataframes containing the growing vulnerability of each group to opioid overdose.</p>
</section>
<section id="ii.-methods" class="level2">
<h2 class="anchored" data-anchor-id="ii.-methods">II. Methods</h2>
<p><br> The data that I am using for this project was retrieved from CORGIS Opioids file (https://corgis-edu.github.io/corgis/datasets/csv/opioids/opioids.csv). This dataset was compiled by the National Institute on Drug Abuse. It contains the number of overdose deaths due to all opioids and subsections of opioids including prescription, synthetic drug, heroin and cocaine. There are also the rate of overdose deaths due to each of these kind of opioids per 100,000 people. <br></p>
<p>Let’s start observing the dataset closely. I called the entire opioid dataset below:</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.patches <span class="im">as</span> mpatches</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>drug<span class="op">=</span>pd.read_csv(<span class="st">'https://corgis-edu.github.io/corgis/datasets/csv/opioids/opioids.csv'</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>drug</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="1">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Year</th>
      <th>Number.All</th>
      <th>Number.Opioid.Any</th>
      <th>Number.Opioid.Prescription</th>
      <th>Number.Opioid.Synthetic</th>
      <th>Number.Opioid.Heroin</th>
      <th>Number.Opioid.Cocaine</th>
      <th>Rate.All.Total</th>
      <th>Rate.All.Sex.Female</th>
      <th>Rate.All.Sex.Male</th>
      <th>...</th>
      <th>Rate.Opioid.Heroin.Race.White</th>
      <th>Rate.Opioid.Heroin.Race.Black</th>
      <th>Rate.Opioid.Heroin.Race.Hispanic</th>
      <th>Rate.Opioid.Cocaine.Total</th>
      <th>Rate.Opioid.Cocaine.Sex.Female</th>
      <th>Rate.Opioid.Cocaine.Sex.Male</th>
      <th>Rate.Opioid.Cocaine.Race.White</th>
      <th>Rate.Opioid.Cocaine.Race.Black</th>
      <th>Rate.Opioid.Cocaine.Race.Hispanic</th>
      <th>Rate.Opioid.Cocaine.Race.American Indian or Alaska Native</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1999</td>
      <td>16849</td>
      <td>8050</td>
      <td>3442</td>
      <td>730</td>
      <td>1960</td>
      <td>3822</td>
      <td>6.1</td>
      <td>3.9</td>
      <td>8.2</td>
      <td>...</td>
      <td>0.7</td>
      <td>0.8</td>
      <td>1.1</td>
      <td>1.4</td>
      <td>0.6</td>
      <td>2.1</td>
      <td>1.0</td>
      <td>3.7</td>
      <td>1.7</td>
      <td>0.9</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2000</td>
      <td>17415</td>
      <td>8407</td>
      <td>3785</td>
      <td>782</td>
      <td>1842</td>
      <td>3544</td>
      <td>6.2</td>
      <td>4.1</td>
      <td>8.3</td>
      <td>...</td>
      <td>0.6</td>
      <td>0.9</td>
      <td>0.9</td>
      <td>1.3</td>
      <td>0.6</td>
      <td>1.9</td>
      <td>1.0</td>
      <td>3.3</td>
      <td>1.3</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2001</td>
      <td>19394</td>
      <td>9496</td>
      <td>4770</td>
      <td>957</td>
      <td>1779</td>
      <td>3833</td>
      <td>6.8</td>
      <td>4.6</td>
      <td>9.0</td>
      <td>...</td>
      <td>0.6</td>
      <td>0.8</td>
      <td>0.9</td>
      <td>1.3</td>
      <td>0.7</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>3.6</td>
      <td>1.3</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2002</td>
      <td>23518</td>
      <td>11920</td>
      <td>6483</td>
      <td>1295</td>
      <td>2089</td>
      <td>4599</td>
      <td>8.2</td>
      <td>5.8</td>
      <td>10.6</td>
      <td>...</td>
      <td>0.7</td>
      <td>0.9</td>
      <td>1.0</td>
      <td>1.6</td>
      <td>0.8</td>
      <td>2.4</td>
      <td>1.3</td>
      <td>4.0</td>
      <td>1.5</td>
      <td>1.1</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2003</td>
      <td>25785</td>
      <td>12940</td>
      <td>7461</td>
      <td>1400</td>
      <td>2080</td>
      <td>5199</td>
      <td>8.9</td>
      <td>6.4</td>
      <td>11.5</td>
      <td>...</td>
      <td>0.7</td>
      <td>0.8</td>
      <td>1.0</td>
      <td>1.8</td>
      <td>0.9</td>
      <td>2.7</td>
      <td>1.6</td>
      <td>4.1</td>
      <td>1.6</td>
      <td>1.7</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2004</td>
      <td>27424</td>
      <td>13756</td>
      <td>8577</td>
      <td>1664</td>
      <td>1878</td>
      <td>5443</td>
      <td>9.4</td>
      <td>6.9</td>
      <td>11.8</td>
      <td>...</td>
      <td>0.7</td>
      <td>0.6</td>
      <td>0.7</td>
      <td>1.9</td>
      <td>1.0</td>
      <td>2.8</td>
      <td>1.7</td>
      <td>4.3</td>
      <td>1.4</td>
      <td>1.6</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2005</td>
      <td>29813</td>
      <td>14918</td>
      <td>9612</td>
      <td>1742</td>
      <td>2009</td>
      <td>6208</td>
      <td>10.1</td>
      <td>7.3</td>
      <td>12.8</td>
      <td>...</td>
      <td>0.7</td>
      <td>0.8</td>
      <td>0.8</td>
      <td>2.1</td>
      <td>1.1</td>
      <td>3.1</td>
      <td>1.9</td>
      <td>4.9</td>
      <td>1.7</td>
      <td>2.3</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2006</td>
      <td>34425</td>
      <td>17545</td>
      <td>11589</td>
      <td>2707</td>
      <td>2088</td>
      <td>7448</td>
      <td>11.5</td>
      <td>8.2</td>
      <td>14.8</td>
      <td>...</td>
      <td>0.8</td>
      <td>0.7</td>
      <td>0.8</td>
      <td>2.5</td>
      <td>1.3</td>
      <td>3.8</td>
      <td>2.3</td>
      <td>5.6</td>
      <td>1.9</td>
      <td>1.6</td>
    </tr>
    <tr>
      <th>8</th>
      <td>2007</td>
      <td>36010</td>
      <td>18516</td>
      <td>12796</td>
      <td>2213</td>
      <td>2399</td>
      <td>6512</td>
      <td>11.9</td>
      <td>8.8</td>
      <td>14.9</td>
      <td>...</td>
      <td>0.9</td>
      <td>0.8</td>
      <td>0.8</td>
      <td>2.2</td>
      <td>1.1</td>
      <td>3.2</td>
      <td>2.0</td>
      <td>4.7</td>
      <td>1.6</td>
      <td>2.1</td>
    </tr>
    <tr>
      <th>9</th>
      <td>2008</td>
      <td>36450</td>
      <td>19582</td>
      <td>13149</td>
      <td>2306</td>
      <td>3041</td>
      <td>5129</td>
      <td>11.9</td>
      <td>8.9</td>
      <td>14.9</td>
      <td>...</td>
      <td>1.2</td>
      <td>0.8</td>
      <td>1.0</td>
      <td>1.7</td>
      <td>0.9</td>
      <td>2.5</td>
      <td>1.6</td>
      <td>3.4</td>
      <td>1.3</td>
      <td>1.5</td>
    </tr>
    <tr>
      <th>10</th>
      <td>2009</td>
      <td>37004</td>
      <td>20422</td>
      <td>13523</td>
      <td>2946</td>
      <td>3278</td>
      <td>4350</td>
      <td>11.9</td>
      <td>9.1</td>
      <td>14.8</td>
      <td>...</td>
      <td>1.3</td>
      <td>0.9</td>
      <td>1.0</td>
      <td>1.4</td>
      <td>0.7</td>
      <td>2.1</td>
      <td>1.3</td>
      <td>3.2</td>
      <td>1.1</td>
      <td>1.8</td>
    </tr>
    <tr>
      <th>11</th>
      <td>2010</td>
      <td>38329</td>
      <td>21089</td>
      <td>14583</td>
      <td>3007</td>
      <td>3036</td>
      <td>4183</td>
      <td>12.3</td>
      <td>9.6</td>
      <td>15.0</td>
      <td>...</td>
      <td>1.2</td>
      <td>0.8</td>
      <td>0.8</td>
      <td>1.3</td>
      <td>0.7</td>
      <td>2.0</td>
      <td>1.2</td>
      <td>3.1</td>
      <td>0.9</td>
      <td>1.9</td>
    </tr>
    <tr>
      <th>12</th>
      <td>2011</td>
      <td>41340</td>
      <td>22784</td>
      <td>15140</td>
      <td>2666</td>
      <td>4397</td>
      <td>4681</td>
      <td>13.2</td>
      <td>10.2</td>
      <td>16.1</td>
      <td>...</td>
      <td>1.8</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.5</td>
      <td>0.8</td>
      <td>2.2</td>
      <td>1.4</td>
      <td>3.1</td>
      <td>1.1</td>
      <td>1.6</td>
    </tr>
    <tr>
      <th>13</th>
      <td>2012</td>
      <td>41502</td>
      <td>23166</td>
      <td>14240</td>
      <td>2628</td>
      <td>5925</td>
      <td>4404</td>
      <td>13.1</td>
      <td>10.2</td>
      <td>16.1</td>
      <td>...</td>
      <td>2.5</td>
      <td>1.3</td>
      <td>1.3</td>
      <td>1.4</td>
      <td>0.8</td>
      <td>2.0</td>
      <td>1.3</td>
      <td>3.0</td>
      <td>1.0</td>
      <td>1.5</td>
    </tr>
    <tr>
      <th>14</th>
      <td>2013</td>
      <td>43982</td>
      <td>25052</td>
      <td>14145</td>
      <td>3105</td>
      <td>8257</td>
      <td>4944</td>
      <td>13.8</td>
      <td>10.6</td>
      <td>17.0</td>
      <td>...</td>
      <td>3.4</td>
      <td>2.0</td>
      <td>1.6</td>
      <td>1.6</td>
      <td>0.9</td>
      <td>2.3</td>
      <td>1.5</td>
      <td>3.4</td>
      <td>1.1</td>
      <td>1.3</td>
    </tr>
    <tr>
      <th>15</th>
      <td>2014</td>
      <td>47055</td>
      <td>28647</td>
      <td>14838</td>
      <td>5544</td>
      <td>10574</td>
      <td>5415</td>
      <td>14.7</td>
      <td>11.1</td>
      <td>18.3</td>
      <td>...</td>
      <td>4.4</td>
      <td>2.5</td>
      <td>1.9</td>
      <td>1.7</td>
      <td>1.0</td>
      <td>2.4</td>
      <td>1.7</td>
      <td>3.4</td>
      <td>1.0</td>
      <td>1.4</td>
    </tr>
    <tr>
      <th>16</th>
      <td>2015</td>
      <td>52404</td>
      <td>33091</td>
      <td>15281</td>
      <td>9580</td>
      <td>12989</td>
      <td>6784</td>
      <td>16.3</td>
      <td>11.8</td>
      <td>20.8</td>
      <td>...</td>
      <td>5.4</td>
      <td>3.1</td>
      <td>2.3</td>
      <td>2.1</td>
      <td>1.2</td>
      <td>3.1</td>
      <td>2.2</td>
      <td>4.0</td>
      <td>1.3</td>
      <td>1.6</td>
    </tr>
    <tr>
      <th>17</th>
      <td>2016</td>
      <td>63632</td>
      <td>42249</td>
      <td>17087</td>
      <td>19413</td>
      <td>15469</td>
      <td>10375</td>
      <td>19.8</td>
      <td>13.4</td>
      <td>26.2</td>
      <td>...</td>
      <td>6.3</td>
      <td>4.5</td>
      <td>2.8</td>
      <td>3.2</td>
      <td>1.8</td>
      <td>4.7</td>
      <td>3.4</td>
      <td>6.1</td>
      <td>2.0</td>
      <td>2.1</td>
    </tr>
    <tr>
      <th>18</th>
      <td>2017</td>
      <td>70237</td>
      <td>47600</td>
      <td>17029</td>
      <td>28466</td>
      <td>15482</td>
      <td>13942</td>
      <td>21.7</td>
      <td>14.4</td>
      <td>29.1</td>
      <td>...</td>
      <td>6.1</td>
      <td>4.9</td>
      <td>2.9</td>
      <td>4.3</td>
      <td>2.5</td>
      <td>6.2</td>
      <td>4.6</td>
      <td>8.3</td>
      <td>2.5</td>
      <td>2.5</td>
    </tr>
    <tr>
      <th>19</th>
      <td>2018</td>
      <td>67367</td>
      <td>46802</td>
      <td>14975</td>
      <td>31335</td>
      <td>14996</td>
      <td>14666</td>
      <td>20.7</td>
      <td>13.6</td>
      <td>27.9</td>
      <td>...</td>
      <td>5.8</td>
      <td>4.9</td>
      <td>3.1</td>
      <td>4.5</td>
      <td>2.6</td>
      <td>6.4</td>
      <td>4.6</td>
      <td>9.0</td>
      <td>3.0</td>
      <td>3.3</td>
    </tr>
    <tr>
      <th>20</th>
      <td>2019</td>
      <td>70630</td>
      <td>49860</td>
      <td>14139</td>
      <td>36359</td>
      <td>14019</td>
      <td>15883</td>
      <td>21.6</td>
      <td>13.7</td>
      <td>29.6</td>
      <td>...</td>
      <td>5.2</td>
      <td>5.0</td>
      <td>3.1</td>
      <td>4.9</td>
      <td>2.7</td>
      <td>7.1</td>
      <td>4.6</td>
      <td>10.7</td>
      <td>3.4</td>
      <td>3.7</td>
    </tr>
  </tbody>
</table>
<p>21 rows × 49 columns</p>
</div>
</div>
</div>
<p>Since I am only focusing on opioid-related overdose deaths, I refined the dataset by removing all the columns that are related to deaths due to ‘all drugs’.</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#redefine drug dataset by dropping following columns.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>drug<span class="op">=</span>drug.drop([<span class="st">'Number.All'</span>, <span class="st">'Rate.All.Total'</span>, <span class="st">'Rate.All.Sex.Female'</span>,<span class="st">'Rate.All.Sex.Male'</span>, <span class="st">'Rate.All.Race.White'</span>, <span class="st">'Rate.All.Race.Black'</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>       <span class="st">'Rate.All.Race.Asian or Pacific Islander'</span>, <span class="st">'Rate.All.Race.Hispanic'</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>       <span class="st">'Rate.All.Race.American Indian or Alaska Native'</span>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>drug</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Year</th>
      <th>Number.Opioid.Any</th>
      <th>Number.Opioid.Prescription</th>
      <th>Number.Opioid.Synthetic</th>
      <th>Number.Opioid.Heroin</th>
      <th>Number.Opioid.Cocaine</th>
      <th>Rate.Opioid.Any.Total</th>
      <th>Rate.Opioid.Any.Sex.Female</th>
      <th>Rate.Opioid.Any.Sex.Male</th>
      <th>Rate.Opioid.Any.Race.White</th>
      <th>...</th>
      <th>Rate.Opioid.Heroin.Race.White</th>
      <th>Rate.Opioid.Heroin.Race.Black</th>
      <th>Rate.Opioid.Heroin.Race.Hispanic</th>
      <th>Rate.Opioid.Cocaine.Total</th>
      <th>Rate.Opioid.Cocaine.Sex.Female</th>
      <th>Rate.Opioid.Cocaine.Sex.Male</th>
      <th>Rate.Opioid.Cocaine.Race.White</th>
      <th>Rate.Opioid.Cocaine.Race.Black</th>
      <th>Rate.Opioid.Cocaine.Race.Hispanic</th>
      <th>Rate.Opioid.Cocaine.Race.American Indian or Alaska Native</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1999</td>
      <td>8050</td>
      <td>3442</td>
      <td>730</td>
      <td>1960</td>
      <td>3822</td>
      <td>2.9</td>
      <td>1.4</td>
      <td>4.3</td>
      <td>2.8</td>
      <td>...</td>
      <td>0.7</td>
      <td>0.8</td>
      <td>1.1</td>
      <td>1.4</td>
      <td>0.6</td>
      <td>2.1</td>
      <td>1.0</td>
      <td>3.7</td>
      <td>1.7</td>
      <td>0.9</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2000</td>
      <td>8407</td>
      <td>3785</td>
      <td>782</td>
      <td>1842</td>
      <td>3544</td>
      <td>3.0</td>
      <td>1.6</td>
      <td>4.4</td>
      <td>3.1</td>
      <td>...</td>
      <td>0.6</td>
      <td>0.9</td>
      <td>0.9</td>
      <td>1.3</td>
      <td>0.6</td>
      <td>1.9</td>
      <td>1.0</td>
      <td>3.3</td>
      <td>1.3</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2001</td>
      <td>9496</td>
      <td>4770</td>
      <td>957</td>
      <td>1779</td>
      <td>3833</td>
      <td>3.3</td>
      <td>1.9</td>
      <td>4.8</td>
      <td>3.7</td>
      <td>...</td>
      <td>0.6</td>
      <td>0.8</td>
      <td>0.9</td>
      <td>1.3</td>
      <td>0.7</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>3.6</td>
      <td>1.3</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2002</td>
      <td>11920</td>
      <td>6483</td>
      <td>1295</td>
      <td>2089</td>
      <td>4599</td>
      <td>4.1</td>
      <td>2.6</td>
      <td>5.7</td>
      <td>4.7</td>
      <td>...</td>
      <td>0.7</td>
      <td>0.9</td>
      <td>1.0</td>
      <td>1.6</td>
      <td>0.8</td>
      <td>2.4</td>
      <td>1.3</td>
      <td>4.0</td>
      <td>1.5</td>
      <td>1.1</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2003</td>
      <td>12940</td>
      <td>7461</td>
      <td>1400</td>
      <td>2080</td>
      <td>5199</td>
      <td>4.5</td>
      <td>2.8</td>
      <td>6.1</td>
      <td>5.2</td>
      <td>...</td>
      <td>0.7</td>
      <td>0.8</td>
      <td>1.0</td>
      <td>1.8</td>
      <td>0.9</td>
      <td>2.7</td>
      <td>1.6</td>
      <td>4.1</td>
      <td>1.6</td>
      <td>1.7</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2004</td>
      <td>13756</td>
      <td>8577</td>
      <td>1664</td>
      <td>1878</td>
      <td>5443</td>
      <td>4.7</td>
      <td>3.1</td>
      <td>6.3</td>
      <td>5.7</td>
      <td>...</td>
      <td>0.7</td>
      <td>0.6</td>
      <td>0.7</td>
      <td>1.9</td>
      <td>1.0</td>
      <td>2.8</td>
      <td>1.7</td>
      <td>4.3</td>
      <td>1.4</td>
      <td>1.6</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2005</td>
      <td>14918</td>
      <td>9612</td>
      <td>1742</td>
      <td>2009</td>
      <td>6208</td>
      <td>5.1</td>
      <td>3.4</td>
      <td>6.6</td>
      <td>6.2</td>
      <td>...</td>
      <td>0.7</td>
      <td>0.8</td>
      <td>0.8</td>
      <td>2.1</td>
      <td>1.1</td>
      <td>3.1</td>
      <td>1.9</td>
      <td>4.9</td>
      <td>1.7</td>
      <td>2.3</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2006</td>
      <td>17545</td>
      <td>11589</td>
      <td>2707</td>
      <td>2088</td>
      <td>7448</td>
      <td>5.9</td>
      <td>3.9</td>
      <td>7.8</td>
      <td>7.3</td>
      <td>...</td>
      <td>0.8</td>
      <td>0.7</td>
      <td>0.8</td>
      <td>2.5</td>
      <td>1.3</td>
      <td>3.8</td>
      <td>2.3</td>
      <td>5.6</td>
      <td>1.9</td>
      <td>1.6</td>
    </tr>
    <tr>
      <th>8</th>
      <td>2007</td>
      <td>18516</td>
      <td>12796</td>
      <td>2213</td>
      <td>2399</td>
      <td>6512</td>
      <td>6.1</td>
      <td>4.3</td>
      <td>8.0</td>
      <td>7.8</td>
      <td>...</td>
      <td>0.9</td>
      <td>0.8</td>
      <td>0.8</td>
      <td>2.2</td>
      <td>1.1</td>
      <td>3.2</td>
      <td>2.0</td>
      <td>4.7</td>
      <td>1.6</td>
      <td>2.1</td>
    </tr>
    <tr>
      <th>9</th>
      <td>2008</td>
      <td>19582</td>
      <td>13149</td>
      <td>2306</td>
      <td>3041</td>
      <td>5129</td>
      <td>6.4</td>
      <td>4.4</td>
      <td>8.4</td>
      <td>8.2</td>
      <td>...</td>
      <td>1.2</td>
      <td>0.8</td>
      <td>1.0</td>
      <td>1.7</td>
      <td>0.9</td>
      <td>2.5</td>
      <td>1.6</td>
      <td>3.4</td>
      <td>1.3</td>
      <td>1.5</td>
    </tr>
    <tr>
      <th>10</th>
      <td>2009</td>
      <td>20422</td>
      <td>13523</td>
      <td>2946</td>
      <td>3278</td>
      <td>4350</td>
      <td>6.6</td>
      <td>4.6</td>
      <td>8.7</td>
      <td>8.6</td>
      <td>...</td>
      <td>1.3</td>
      <td>0.9</td>
      <td>1.0</td>
      <td>1.4</td>
      <td>0.7</td>
      <td>2.1</td>
      <td>1.3</td>
      <td>3.2</td>
      <td>1.1</td>
      <td>1.8</td>
    </tr>
    <tr>
      <th>11</th>
      <td>2010</td>
      <td>21089</td>
      <td>14583</td>
      <td>3007</td>
      <td>3036</td>
      <td>4183</td>
      <td>6.8</td>
      <td>4.9</td>
      <td>8.7</td>
      <td>9.1</td>
      <td>...</td>
      <td>1.2</td>
      <td>0.8</td>
      <td>0.8</td>
      <td>1.3</td>
      <td>0.7</td>
      <td>2.0</td>
      <td>1.2</td>
      <td>3.1</td>
      <td>0.9</td>
      <td>1.9</td>
    </tr>
    <tr>
      <th>12</th>
      <td>2011</td>
      <td>22784</td>
      <td>15140</td>
      <td>2666</td>
      <td>4397</td>
      <td>4681</td>
      <td>7.3</td>
      <td>5.2</td>
      <td>9.4</td>
      <td>9.7</td>
      <td>...</td>
      <td>1.8</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.5</td>
      <td>0.8</td>
      <td>2.2</td>
      <td>1.4</td>
      <td>3.1</td>
      <td>1.1</td>
      <td>1.6</td>
    </tr>
    <tr>
      <th>13</th>
      <td>2012</td>
      <td>23166</td>
      <td>14240</td>
      <td>2628</td>
      <td>5925</td>
      <td>4404</td>
      <td>7.4</td>
      <td>5.3</td>
      <td>9.5</td>
      <td>9.8</td>
      <td>...</td>
      <td>2.5</td>
      <td>1.3</td>
      <td>1.3</td>
      <td>1.4</td>
      <td>0.8</td>
      <td>2.0</td>
      <td>1.3</td>
      <td>3.0</td>
      <td>1.0</td>
      <td>1.5</td>
    </tr>
    <tr>
      <th>14</th>
      <td>2013</td>
      <td>25052</td>
      <td>14145</td>
      <td>3105</td>
      <td>8257</td>
      <td>4944</td>
      <td>7.9</td>
      <td>5.6</td>
      <td>10.2</td>
      <td>10.5</td>
      <td>...</td>
      <td>3.4</td>
      <td>2.0</td>
      <td>1.6</td>
      <td>1.6</td>
      <td>0.9</td>
      <td>2.3</td>
      <td>1.5</td>
      <td>3.4</td>
      <td>1.1</td>
      <td>1.3</td>
    </tr>
    <tr>
      <th>15</th>
      <td>2014</td>
      <td>28647</td>
      <td>14838</td>
      <td>5544</td>
      <td>10574</td>
      <td>5415</td>
      <td>9.0</td>
      <td>6.3</td>
      <td>11.7</td>
      <td>12.0</td>
      <td>...</td>
      <td>4.4</td>
      <td>2.5</td>
      <td>1.9</td>
      <td>1.7</td>
      <td>1.0</td>
      <td>2.4</td>
      <td>1.7</td>
      <td>3.4</td>
      <td>1.0</td>
      <td>1.4</td>
    </tr>
    <tr>
      <th>16</th>
      <td>2015</td>
      <td>33091</td>
      <td>15281</td>
      <td>9580</td>
      <td>12989</td>
      <td>6784</td>
      <td>10.4</td>
      <td>7.1</td>
      <td>13.7</td>
      <td>13.9</td>
      <td>...</td>
      <td>5.4</td>
      <td>3.1</td>
      <td>2.3</td>
      <td>2.1</td>
      <td>1.2</td>
      <td>3.1</td>
      <td>2.2</td>
      <td>4.0</td>
      <td>1.3</td>
      <td>1.6</td>
    </tr>
    <tr>
      <th>17</th>
      <td>2016</td>
      <td>42249</td>
      <td>17087</td>
      <td>19413</td>
      <td>15469</td>
      <td>10375</td>
      <td>13.3</td>
      <td>8.5</td>
      <td>18.1</td>
      <td>17.5</td>
      <td>...</td>
      <td>6.3</td>
      <td>4.5</td>
      <td>2.8</td>
      <td>3.2</td>
      <td>1.8</td>
      <td>4.7</td>
      <td>3.4</td>
      <td>6.1</td>
      <td>2.0</td>
      <td>2.1</td>
    </tr>
    <tr>
      <th>18</th>
      <td>2017</td>
      <td>47600</td>
      <td>17029</td>
      <td>28466</td>
      <td>15482</td>
      <td>13942</td>
      <td>14.9</td>
      <td>9.4</td>
      <td>20.4</td>
      <td>19.4</td>
      <td>...</td>
      <td>6.1</td>
      <td>4.9</td>
      <td>2.9</td>
      <td>4.3</td>
      <td>2.5</td>
      <td>6.2</td>
      <td>4.6</td>
      <td>8.3</td>
      <td>2.5</td>
      <td>2.5</td>
    </tr>
    <tr>
      <th>19</th>
      <td>2018</td>
      <td>46802</td>
      <td>14975</td>
      <td>31335</td>
      <td>14996</td>
      <td>14666</td>
      <td>14.6</td>
      <td>9.0</td>
      <td>20.1</td>
      <td>18.6</td>
      <td>...</td>
      <td>5.8</td>
      <td>4.9</td>
      <td>3.1</td>
      <td>4.5</td>
      <td>2.6</td>
      <td>6.4</td>
      <td>4.6</td>
      <td>9.0</td>
      <td>3.0</td>
      <td>3.3</td>
    </tr>
    <tr>
      <th>20</th>
      <td>2019</td>
      <td>49860</td>
      <td>14139</td>
      <td>36359</td>
      <td>14019</td>
      <td>15883</td>
      <td>15.5</td>
      <td>9.3</td>
      <td>21.7</td>
      <td>19.0</td>
      <td>...</td>
      <td>5.2</td>
      <td>5.0</td>
      <td>3.1</td>
      <td>4.9</td>
      <td>2.7</td>
      <td>7.1</td>
      <td>4.6</td>
      <td>10.7</td>
      <td>3.4</td>
      <td>3.7</td>
    </tr>
  </tbody>
</table>
<p>21 rows × 40 columns</p>
</div>
</div>
</div>
<p>While I cleared some irrelevant columns, the dataset still hides some columns due to its massive size. Thus, let’s print out all the columns’ names below:</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>drug.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>Index(['Year', 'Number.Opioid.Any', 'Number.Opioid.Prescription',
       'Number.Opioid.Synthetic', 'Number.Opioid.Heroin',
       'Number.Opioid.Cocaine', 'Rate.Opioid.Any.Total',
       'Rate.Opioid.Any.Sex.Female', 'Rate.Opioid.Any.Sex.Male',
       'Rate.Opioid.Any.Race.White', 'Rate.Opioid.Any.Race.Black',
       'Rate.Opioid.Any.Race.Asian or Pacific Islander',
       'Rate.Opioid.Any.Race.Hispanic',
       'Rate.Opioid.Any.Race.American Indian or Alaska Native',
       'Rate.Opioid.Prescription.Total', 'Rate.Opioid.Prescription.Sex.Female',
       'Rate.Opioid.Prescription.Sex.Male',
       'Rate.Opioid.Prescription.Race.White',
       'Rate.Opioid.Prescription.Race.Black',
       'Rate.Opioid.Prescription.Race.Hispanic',
       'Rate.Opioid.Prescription.Race.American Indian or Alaska Native',
       'Rate.Opioid.Synthetic.Total', 'Rate.Opioid.Synthetic.Sex.Female',
       'Rate.Opioid.Synthetic.Sex.Male', 'Rate.Opioid.Synthetic.Race.White',
       'Rate.Opioid.Synthetic.Race.Black',
       'Rate.Opioid.Synthetic.Race.Hispanic', 'Rate.Opioid.Heroin.Total',
       'Rate.Opioid.Heroin.Sex.Female', 'Rate.Opioid.Heroin.Sex.Male',
       'Rate.Opioid.Heroin.Race.White', 'Rate.Opioid.Heroin.Race.Black',
       'Rate.Opioid.Heroin.Race.Hispanic', 'Rate.Opioid.Cocaine.Total',
       'Rate.Opioid.Cocaine.Sex.Female', 'Rate.Opioid.Cocaine.Sex.Male',
       'Rate.Opioid.Cocaine.Race.White', 'Rate.Opioid.Cocaine.Race.Black',
       'Rate.Opioid.Cocaine.Race.Hispanic',
       'Rate.Opioid.Cocaine.Race.American Indian or Alaska Native'],
      dtype='object')</code></pre>
</div>
</div>
</section>
<section id="iii.-results" class="level2">
<h2 class="anchored" data-anchor-id="iii.-results">III. Results</h2>
<p>Now that I spent enough time looking through the dataset, I began the main section of analysis to answer the research question by analyzing the overall overdose rate of <strong><em>all opioids</em></strong>. As my first step, I converted columns of dataframe into lists. As the x-axis of each graph is the year, I created a new list called ‘year’ from the ‘year’ column in drug dataset. Then, to analyze the growth rate of each group of race and sex, I repeated converting dataframe into lists to effectively plot multiple lines and some bars in order to see the growth easily.</p>
<section id="any-opioid-overdose-death-rate-by-sex" class="level3">
<h3 class="anchored" data-anchor-id="any-opioid-overdose-death-rate-by-sex">Any Opioid Overdose Death Rate by Sex</h3>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#convert the Rate.Opioid.Any.Sex.Female and Rate.Opioid.Any.Sex.Male columns to lists</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>year<span class="op">=</span>drug[<span class="st">'Year'</span>].values.tolist()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>rate_any_female<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Any.Sex.Female'</span>].values.tolist()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>rate_any_male<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Any.Sex.Male'</span>].values.tolist()</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>plt.bar(year, rate_any_female, color<span class="op">=</span><span class="st">'green'</span>, label<span class="op">=</span><span class="st">'female'</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>plt.bar(year, rate_any_male, bottom<span class="op">=</span>rate_any_female, color<span class="op">=</span><span class="st">'grey'</span>,label<span class="op">=</span><span class="st">'male'</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>plt.plot(year, rate_any_female, label<span class="op">=</span><span class="st">'female'</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>plt.plot(year, rate_any_male, label<span class="op">=</span><span class="st">'male'</span>, color<span class="op">=</span><span class="st">'orange'</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>plt.legend(loc<span class="op">=</span><span class="st">'upper left'</span>, frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Total Rates (female+male)'</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Any Opioid Overdose Death Rate by Sex'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>Text(0.5, 1.0, 'Any Opioid Overdose Death Rate by Sex')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="opioid_files/figure-html/cell-5-output-2.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="any-opioid-overdose-death-rate-by-race" class="level3">
<h3 class="anchored" data-anchor-id="any-opioid-overdose-death-rate-by-race">Any Opioid Overdose Death Rate by Race</h3>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#convert the Rate.Opioid.Any columns for races to lists</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>rate_any_white<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Any.Race.White'</span>].values.tolist()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>rate_any_black<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Any.Race.Black'</span>].values.tolist()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>rate_any_asian<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Any.Race.Asian or Pacific Islander'</span>].values.tolist()</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>rate_any_hispanic<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Any.Race.Hispanic'</span>].values.tolist()</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>rate_any_indian<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Any.Race.American Indian or Alaska Native'</span>].values.tolist()</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>plt.plot(year,rate_any_white, label<span class="op">=</span><span class="st">'White'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>plt.plot(year,rate_any_black, label<span class="op">=</span><span class="st">'Black'</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>plt.plot(year,rate_any_asian, label<span class="op">=</span><span class="st">'Asian or Pacific Islander'</span>, linestyle<span class="op">=</span><span class="st">':'</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>plt.plot(year,rate_any_hispanic, label<span class="op">=</span><span class="st">'Hispanic'</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>plt.plot(year,rate_any_indian, label<span class="op">=</span><span class="st">'American Indian or Alaska Native'</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>plt.legend(loc<span class="op">=</span><span class="st">'upper left'</span>, frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Any Opioid Overdose Death Rate by Race'</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rate'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>Text(0, 0.5, 'Rate')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="opioid_files/figure-html/cell-6-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>Now that I observed the overall picture of the all opioid overdose growth, I started to dig deeper into analyzing the overdose growth of a <strong><em>specific opioid</em></strong> drug based on sex and race. The process is somewhat different. First, I obtained data from each column in the dataframe called drug. Then I added these values to a new empty list and created another empty list to store calcuated slopes only. Next, I wrote a for loop that goes through each group’s values, makes a scatterplot, calculate slopes using pyplot, plots the linear regression and appends the slopes to a list. Lastly, I changed design of the graph by adding title for each axis, main title and legend.</p>
</section>
<section id="prescription-overdose-death-growth-by-sex" class="level3">
<h3 class="anchored" data-anchor-id="prescription-overdose-death-growth-by-sex">Prescription Overdose Death Growth by Sex</h3>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get data from each column.</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>rate_presc_female<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Prescription.Sex.Female'</span>]</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>rate_presc_male<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Prescription.Sex.Male'</span>]</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>rate_presc_sex<span class="op">=</span>[]</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>rate_presc_sex.append(rate_presc_female)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>rate_presc_sex.append(rate_presc_male)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for slopes.</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>slope_presc_sex<span class="op">=</span>[]</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> rate_presc_sex:</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>year</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>i</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="co">#make a scatterplot</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    plt.scatter(x,y)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="co">#calculate slope</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    a,b<span class="op">=</span>np.polyfit(x,y,<span class="dv">1</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    slope_presc_sex.append(a)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, a<span class="op">*</span>np.array(x)<span class="op">+</span>b)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    <span class="co">#plot the linear regression</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(slope_presc_sex)</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating legend with color box</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>presc_fem <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'female'</span>)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>presc_male <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'orange'</span>, label<span class="op">=</span><span class="st">'male'</span>)</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>plt.legend(handles<span class="op">=</span>[presc_fem,presc_male])</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rate'</span>)</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Prescription Overdose Death Growth by Sex'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[0.1657142857142838, 0.19051948051947903]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>Text(0.5, 1.0, 'Prescription Overdose Death Growth by Sex')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="opioid_files/figure-html/cell-7-output-3.png" class="img-fluid"></p>
</div>
</div>
<p>In order to determine whether linear or polynomial regression is more appropriate, I created a graph of polynomial regression below as a test. Since slope is only applicable for linear regression, I took a derivative which turned out to be -0.02592 and -0.04141 for female and male groups. According to the shape, this negative slope might be true. However, in terms of the overall trend, the rate of overdose death due to prescription opioid definitely grew over the years. Therefore, for the remainder of analysis, I decided to use linear regression which would better provide the relationship between the rate and year in a simplest manner.</p>
</section>
<section id="prescription-overdose-death-growth-by-sex-polynomial-regression" class="level3">
<h3 class="anchored" data-anchor-id="prescription-overdose-death-growth-by-sex-polynomial-regression">Prescription Overdose Death Growth by Sex (POLYNOMIAL REGRESSION)</h3>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>rate_presc_females<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Prescription.Sex.Female'</span>]</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>rate_presc_males<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Prescription.Sex.Male'</span>]</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>rate_presc_sexual<span class="op">=</span>[]</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>rate_presc_sexual.append(rate_presc_females)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>rate_presc_sexual.append(rate_presc_males)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co">#create polynomial regression.</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> rate_presc_sexual:</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>year</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>i</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    plt.scatter(x,y)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    poly_fit<span class="op">=</span>np.poly1d(np.polyfit(x,y,<span class="dv">2</span>))</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="co">#slope is the derivative of polynomial regression.</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    slope<span class="op">=</span> poly_fit.deriv()</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    xx <span class="op">=</span> np.linspace(<span class="dv">1999</span>, <span class="dv">2019</span>, <span class="dv">11</span>)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    plt.plot(xx, poly_fit(xx), c<span class="op">=</span><span class="st">'r'</span>,linestyle<span class="op">=</span><span class="st">'-'</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(slope)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating legend with color box</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>presc_fem <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'female'</span>)</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>presc_male <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'orange'</span>, label<span class="op">=</span><span class="st">'male'</span>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>plt.legend(handles<span class="op">=</span>[presc_fem,presc_male])</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rate'</span>)</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Prescription Overdose Death Growth by Sex (POLYNOMIAL REGRESSION)'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 
-0.02592 x + 52.24
 
-0.04141 x + 83.38</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>Text(0.5, 1.0, 'Prescription Overdose Death Growth by Sex (POLYNOMIAL REGRESSION)')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="opioid_files/figure-html/cell-8-output-3.png" class="img-fluid"></p>
</div>
</div>
<p>For the following analysis by race, some group data is missing unfortuantely. For the prescription overdose death growth below, data of Asian or Pacific Islanders is not available. For the sake of this project, I will still analyze all the avilable data in this datasource. However, this can be a room for improvement by compiling or finding a more comprehensive dataset in the future.</p>
</section>
<section id="prescription-overdose-death-growth-by-race" class="level3">
<h3 class="anchored" data-anchor-id="prescription-overdose-death-growth-by-race">Prescription Overdose Death Growth by Race</h3>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get data from each column (Asian or Pacific Islander data is missing).</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>rate_presc_white<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Prescription.Race.White'</span>]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>rate_presc_black<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Prescription.Race.Black'</span>]</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>rate_presc_hispanic<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Prescription.Race.Hispanic'</span>]</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>rate_presc_indian<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Prescription.Race.American Indian or Alaska Native'</span>]</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for prescription overdose death rate by race.</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>rate_presc_race<span class="op">=</span>[]</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>rate_presc_race.append(rate_presc_white)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>rate_presc_race.append(rate_presc_black)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>rate_presc_race.append(rate_presc_hispanic)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>rate_presc_race.append(rate_presc_indian)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for slopes.</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>slope_presc_race<span class="op">=</span>[]</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> rate_presc_race:</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>year</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>i</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">#make a scatterplot</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>    plt.scatter(x,y)</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>    <span class="co">#calculate slope</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>    a,b<span class="op">=</span>np.polyfit(x,y,<span class="dv">1</span>)</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>    slope_presc_race.append(a)</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>    <span class="co">#plot the linear regression</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, a<span class="op">*</span>np.array(x)<span class="op">+</span>b)</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(slope_presc_race)</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating legend with color box</span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>presc_white <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>presc_black <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'orange'</span>, label<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>presc_hispanic <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'green'</span>, label<span class="op">=</span><span class="st">'hispanic'</span>)</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>presc_indian <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'red'</span>, label<span class="op">=</span><span class="st">'indian'</span>)</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>plt.legend(handles<span class="op">=</span>[presc_white,presc_black,presc_hispanic,presc_indian])</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rate'</span>)</span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Prescription Overdose Death Growth by Race'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[0.2529870129870105, 0.13389610389610124, 0.039999999999998814, 0.2605194805194794]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>Text(0.5, 1.0, 'Prescription Overdose Death Growth by Race')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="opioid_files/figure-html/cell-9-output-3.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="synthetic-overdose-death-growth-by-sex" class="level3">
<h3 class="anchored" data-anchor-id="synthetic-overdose-death-growth-by-sex">Synthetic Overdose Death Growth by Sex</h3>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get data from each column.</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>rate_synth_female<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Synthetic.Sex.Female'</span>]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>rate_synth_male<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Synthetic.Sex.Male'</span>]</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for synthetic overdose death rate by sex.</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>rate_synth_sex<span class="op">=</span>[]</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>rate_synth_sex.append(rate_synth_female)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>rate_synth_sex.append(rate_synth_male)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for slopes.</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>slope_synth_sex<span class="op">=</span>[]</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> rate_synth_sex:</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>year</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>i</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="co">#make a scatterplot</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    plt.scatter(x,y)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    <span class="co">#calculate slope</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    a,b<span class="op">=</span>np.polyfit(x,y,<span class="dv">1</span>)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>    slope_synth_sex.append(a)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">#plot the linear regression</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, a<span class="op">*</span>np.array(x)<span class="op">+</span>b)</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(slope_synth_sex)</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating legend with color box</span></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>synth_fem <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'female'</span>)</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>synth_male <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'orange'</span>, label<span class="op">=</span><span class="st">'male'</span>)</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>plt.legend(handles<span class="op">=</span>[synth_fem,synth_male])</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rate'</span>)</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Synthetic Overdose Death Growth by Sex'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[0.23649350649350034, 0.6229870129869955]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>Text(0.5, 1.0, 'Synthetic Overdose Death Growth by Sex')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="opioid_files/figure-html/cell-10-output-3.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="synthetic-overdose-death-growth-by-race" class="level3">
<h3 class="anchored" data-anchor-id="synthetic-overdose-death-growth-by-race">Synthetic Overdose Death Growth by Race</h3>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get data from each column (Asian or Pacific Islander and American Indian or Native Alaskan data are missing).</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>rate_synth_white<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Synthetic.Race.White'</span>]</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>rate_synth_black<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Synthetic.Race.Black'</span>]</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>rate_synth_hispanic<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Synthetic.Race.Hispanic'</span>]</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for synthetic overdose death rate by race.</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>rate_synth_race<span class="op">=</span>[]</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>rate_synth_race.append(rate_synth_white)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>rate_synth_race.append(rate_synth_black)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>rate_synth_race.append(rate_synth_hispanic)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for slopes.</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>slope_synth_race<span class="op">=</span>[]</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> rate_synth_race:</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>year</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>i</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    <span class="co">#make a scatterplot</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>    plt.scatter(x,y)</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">#calculate slope</span></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>    a,b<span class="op">=</span>np.polyfit(x,y,<span class="dv">1</span>)</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    slope_synth_race.append(a)</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>    <span class="co">#plot the linear regression</span></span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, a<span class="op">*</span>np.array(x)<span class="op">+</span>b)</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(slope_synth_race)</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating legend with color box</span></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>synth_white <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>synth_black <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'orange'</span>, label<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>synth_hispanic <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'green'</span>, label<span class="op">=</span><span class="st">'hispanic'</span>)</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>plt.legend(handles<span class="op">=</span>[synth_white,synth_black,synth_hispanic])</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rate'</span>)</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Synthetic Overdose Death Growth by Race'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[0.5502597402597247, 0.47181818181816904, 0.20402597402596873]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>Text(0.5, 1.0, 'Synthetic Overdose Death Growth by Race')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="opioid_files/figure-html/cell-11-output-3.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="heroin-overdose-death-growth-by-sex" class="level3">
<h3 class="anchored" data-anchor-id="heroin-overdose-death-growth-by-sex">Heroin Overdose Death Growth by Sex</h3>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get data from each column.</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>rate_heroin_female<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Heroin.Sex.Female'</span>]</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>rate_heroin_male<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Heroin.Sex.Male'</span>]</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for heroin overdose death rate by sex.</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>rate_heroin_sex<span class="op">=</span>[]</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>rate_heroin_sex.append(rate_heroin_female)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>rate_heroin_sex.append(rate_heroin_male)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for slopes.</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>slope_heroin_sex<span class="op">=</span>[]</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> rate_heroin_sex:</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>year</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>i</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    <span class="co">#make a scatterplot</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    plt.scatter(x,y)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>    <span class="co">#calculate slope</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>    a,b<span class="op">=</span>np.polyfit(x,y,<span class="dv">1</span>)</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>    slope_heroin_sex.append(a)</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">#plot the linear regression</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, a<span class="op">*</span>np.array(x)<span class="op">+</span>b)</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(slope_heroin_sex)</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating legend with color box</span></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>heroin_fem <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'female'</span>)</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>heroin_male <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'orange'</span>, label<span class="op">=</span><span class="st">'male'</span>)</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>plt.legend(handles<span class="op">=</span>[heroin_fem,heroin_male])</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rate'</span>)</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Heroin Overdose Death Growth by Sex'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[0.12532467532467176, 0.35545454545453514]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>Text(0.5, 1.0, 'Heroin Overdose Death Growth by Sex')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="opioid_files/figure-html/cell-12-output-3.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="heroin-overdose-death-growth-by-race" class="level3">
<h3 class="anchored" data-anchor-id="heroin-overdose-death-growth-by-race">Heroin Overdose Death Growth by Race</h3>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get data from each column (Asian or Pacific Islander and American Indian or Native Alaskan data are missing).</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>rate_heroin_white<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Heroin.Race.White'</span>]</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>rate_heroin_black<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Heroin.Race.Black'</span>]</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>rate_heroin_hispanic<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Heroin.Race.Hispanic'</span>]</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for heroin overdose death rate by race.</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>rate_heroin_race<span class="op">=</span>[]</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>rate_heroin_race.append(rate_heroin_white)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>rate_heroin_race.append(rate_heroin_black)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>rate_heroin_race.append(rate_heroin_hispanic)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for slopes.</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>slope_heroin_race<span class="op">=</span>[]</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> rate_heroin_race:</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>year</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>i</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>    <span class="co">#make a scatterplot</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>    plt.scatter(x,y)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">#calculate slope</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    a,b<span class="op">=</span>np.polyfit(x,y,<span class="dv">1</span>)</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>    slope_heroin_race.append(a)</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>    <span class="co">#plot the linear regression</span></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, a<span class="op">*</span>np.array(x)<span class="op">+</span>b)</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(slope_heroin_race)</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating legend with color box</span></span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>heroin_white <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'orange'</span>, label<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>heroin_black <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>heroin_hispanic <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'green'</span>, label<span class="op">=</span><span class="st">'hispanic'</span>)</span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>plt.legend(handles<span class="op">=</span>[heroin_white,heroin_black,heroin_hispanic])</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rate'</span>)</span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Heroin Overdose Death Growth by Race'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[0.310909090909082, 0.21597402597401968, 0.11311688311687951]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>Text(0.5, 1.0, 'Heroin Overdose Death Growth by Race')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="opioid_files/figure-html/cell-13-output-3.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="cocaine-overdose-death-growth-by-sex" class="level3">
<h3 class="anchored" data-anchor-id="cocaine-overdose-death-growth-by-sex">Cocaine Overdose Death Growth by Sex</h3>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get data from each column.</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>rate_cocaine_female<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Cocaine.Sex.Female'</span>]</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>rate_cocaine_male<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Cocaine.Sex.Male'</span>]</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for cocaine overdose death rate by sex.</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>rate_cocaine_sex<span class="op">=</span>[]</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>rate_cocaine_sex.append(rate_cocaine_female)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>rate_cocaine_sex.append(rate_cocaine_male)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for slopes.</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>slope_cocaine_sex<span class="op">=</span>[]</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> rate_cocaine_sex:</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>year</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>i</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>    <span class="co">#make a scatterplot</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>    plt.scatter(x,y)</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    <span class="co">#calculate slope</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    a,b<span class="op">=</span>np.polyfit(x,y,<span class="dv">1</span>)</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>    slope_cocaine_sex.append(a)</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">#plot the linear regression</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, a<span class="op">*</span>np.array(x)<span class="op">+</span>b)</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(slope_cocaine_sex)</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating legend with color box</span></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>cocaine_fem <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'female'</span>)</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>cocaine_male <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'orange'</span>, label<span class="op">=</span><span class="st">'male'</span>)</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>plt.legend(handles<span class="op">=</span>[cocaine_fem,cocaine_male])</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rate'</span>)</span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Cocaine Overdose Death Growth by Sex'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[0.07675324675324491, 0.16818181818181396]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>Text(0.5, 1.0, 'Cocaine Overdose Death Growth by Sex')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="opioid_files/figure-html/cell-14-output-3.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="cocaine-overdose-death-growth-by-race" class="level3">
<h3 class="anchored" data-anchor-id="cocaine-overdose-death-growth-by-race">Cocaine Overdose Death Growth by Race</h3>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get data from each column (Asian or Pacific Islander data is missing).</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>rate_cocaine_white<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Cocaine.Race.White'</span>]</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>rate_cocaine_black<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Cocaine.Race.Black'</span>]</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>rate_cocaine_hispanic<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Cocaine.Race.Hispanic'</span>]</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>rate_cocaine_indian<span class="op">=</span>drug[<span class="st">'Rate.Opioid.Cocaine.Race.American Indian or Alaska Native'</span>]</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for cocaine overdose death rate by race.</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>rate_cocaine_race<span class="op">=</span>[]</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>rate_cocaine_race.append(rate_cocaine_white)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>rate_cocaine_race.append(rate_cocaine_black)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>rate_cocaine_race.append(rate_cocaine_hispanic)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>rate_cocaine_race.append(rate_cocaine_indian)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="co">#empty list for slopes.</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>slope_cocaine_race<span class="op">=</span>[]</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> rate_cocaine_race:</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>year</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>i</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">#make a scatterplot</span></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>    plt.scatter(x,y)</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>    <span class="co">#calculate slope</span></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>    a,b<span class="op">=</span>np.polyfit(x,y,<span class="dv">1</span>)</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>    slope_cocaine_race.append(a)</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>    <span class="co">#plot the linear regression</span></span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, a<span class="op">*</span>np.array(x)<span class="op">+</span>b)</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(slope_cocaine_race)</span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating legend with color box</span></span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>cocaine_white <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a>cocaine_black <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'orange'</span>, label<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a>cocaine_hispanic <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'green'</span>, label<span class="op">=</span><span class="st">'hispanic'</span>)</span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a>cocaine_indian <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'red'</span>, label<span class="op">=</span><span class="st">'indian'</span>)</span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a>plt.legend(handles<span class="op">=</span>[cocaine_white,cocaine_black,cocaine_hispanic,cocaine_indian])</span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rate'</span>)</span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Cocaine Overdose Death Growth by Race'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[0.14194805194804838, 0.1963636363636313, 0.045584415584413736, 0.07948051948051858]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>Text(0.5, 1.0, 'Cocaine Overdose Death Growth by Race')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="opioid_files/figure-html/cell-15-output-3.png" class="img-fluid"></p>
</div>
</div>
<p>Now that I have calcuated slopes of all the groups, I compiled them into two separate dataframes (one for sex and another for race).</p>
</section>
<section id="dataframe-1-growth-rate-of-overdose-death-by-sex" class="level3">
<h3 class="anchored" data-anchor-id="dataframe-1-growth-rate-of-overdose-death-by-sex">Dataframe #1: Growth Rate of Overdose Death by Sex</h3>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create a dataframe with slopes of all drugs by sex.</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>overdose_by_sex<span class="op">=</span> {<span class="st">'Sex'</span>:[<span class="st">'Female'</span>,<span class="st">'Male'</span>],</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Prescription'</span>:slope_presc_sex,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Synthetic'</span>:slope_synth_sex,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Heroin'</span>:slope_heroin_sex,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Cocaine'</span>:slope_cocaine_sex }</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>overdose_sex <span class="op">=</span> pd.DataFrame(overdose_by_sex)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(overdose_sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Sex  Prescription  Synthetic    Heroin   Cocaine
0  Female      0.165714   0.236494  0.125325  0.076753
1    Male      0.190519   0.622987  0.355455  0.168182</code></pre>
</div>
</div>
</section>
<section id="dataframe-2-growth-rate-of-overdose-death-by-race" class="level3">
<h3 class="anchored" data-anchor-id="dataframe-2-growth-rate-of-overdose-death-by-race">Dataframe #2: Growth Rate of Overdose Death by Race</h3>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create a dataframe with slopes of all drugs by race (I excluded Asian or Pacific Islander since there is no data on them for any of drugs).</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co">#For synthetic and heroin, no data of American Indian or Alaska Native; Thus, adding NaN value to make the array length equal.</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>overdose_by_race<span class="op">=</span> {<span class="st">'Race'</span>:[<span class="st">'White'</span>,<span class="st">'Black'</span>,<span class="st">'Hispanic'</span>,<span class="st">'American Indian or Alaska Native'</span>],</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Prescription'</span>:slope_presc_race,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Synthetic'</span>:[<span class="fl">0.675</span>, <span class="fl">0.705</span>, <span class="fl">0.31</span>, <span class="st">'NaN'</span>],</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Heroin'</span>:[<span class="fl">0.225</span>, <span class="fl">0.21000000000000002</span>, <span class="fl">0.1</span>, <span class="st">'NaN'</span>],</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Cocaine'</span>:slope_cocaine_race }</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>overdose_race <span class="op">=</span> pd.DataFrame(overdose_by_race)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(overdose_race)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               Race  Prescription Synthetic Heroin   Cocaine
0                             White      0.252987     0.675  0.225  0.141948
1                             Black      0.133896     0.705   0.21  0.196364
2                          Hispanic      0.040000      0.31    0.1  0.045584
3  American Indian or Alaska Native      0.260519       NaN    NaN  0.079481</code></pre>
</div>
</div>
</section>
</section>
<section id="iv.-discussion" class="level2">
<h2 class="anchored" data-anchor-id="iv.-discussion">IV. Discussion</h2>
<p>The analysis in the Result section provides a comprehensive overview as well as detailed information on the growth of overdose death for each group by sex and gender. Below, I described these findings more in depth and answered the research question.</p>
<section id="big-picture-overall-opioid-overdose-by-sex-and-race" class="level3">
<h3 class="anchored" data-anchor-id="big-picture-overall-opioid-overdose-by-sex-and-race">Big Picture: Overall Opioid Overdose by Sex and Race</h3>
<p>Referring to “Any Opioid Overdose Death Rate by Sex” graph, it is very clear that male population not only accounted for greater portion of overdose death, but also displayed higher growth rate from 1999 to 2019 in the United States. Looking at “Any Opioid Overdose Death Rate by Race” graph, white population showed the highest rate of death and illustrates similar growth level with American Indian or Alaska Native group among others. Black and Hispanic groups have similar trend until 2015 as black group skyrocketed in its overdose rate. Throughout the years, Asian or Pacific Islander remained very close to 0% rate. Thus, in all of the analysis on each opioid type, this group’s data is missing.</p>
</section>
<section id="examination-of-dataframes" class="level3">
<h3 class="anchored" data-anchor-id="examination-of-dataframes">Examination of Dataframes</h3>
<p>Dataframe #1 shows the overview of opioid overdose death growth rate by sex for each drug type. For female group, synthetic opioid grew the most from 1999 to 2019 with the growth rate of 0.236494. Prescription opioid with 0.165714, heroin with 0.125325 and cocaine with 0.076753 followed in order. For male group, synthetic opioid also had the highest growth rate of 0.622987 which was followed by heroin (0.355455), prescription opioid (0.190519) and cocaine (0.168182).</p>
<p>Dataframe #2 displays the growth rate of overdose death by race for each type of opioid. For white group, synthetic opioid showed the highest growth rate of 0.675, followed by prescription opioid (0.252987), heroin (0.225) and cocaine (0.141948). For black group, synthetic opioid grew the most with the rate of 0.705, followed by heroin (0.21), cocaine (0.196364) and prescription opioid (0.133896). For hispanic group, synthetic opioid also displayed the highest overdose growth rate of 0.31, followed by heroin (0.1), cocaine (0.045584) and prescription opioid (0.04). For American Indian or Alaska Native group, data on synthetic and heroin overdose are unavailable. Among available datapoints, prescription opioid showed the highest growth rate of 0.260519, followed by cocaine (0.079481).</p>
<p>These findings overall somewhat match my expectation and how the media portrays the opioid crisis in the United States:</p>
<p><strong><em>Expected</em></strong> - Synthetic opioid is the greatest cause of substantially increasing overdose among other types. - Male and white groups would have been affected the most with highest growth rate of opioid overdose deaths. - Black and hispanic groups would be the next in risk.</p>
<p><strong><em>Unexpected</em></strong> - I was not aware that high number of American Indian and Alaska Natives lost their lives due to opioid overdose. - Contrary to my belief that prescription opioid would be less deadly, it actually is higher up in the rank in terms of deadliness.</p>
</section>
<section id="commality-contextual-observation" class="level3">
<h3 class="anchored" data-anchor-id="commality-contextual-observation">Commality &amp; Contextual Observation</h3>
<section id="common-inflection-point" class="level4">
<h4 class="anchored" data-anchor-id="common-inflection-point">1. Common Inflection Point</h4>
<p>For almost all graphs on each opioid drug type, both by sex and race, the <strong>year of 2013</strong> was a common inflection point which led to a drastic increase in the overdose death rate. Thus, I researched about events that happened in the United States around that time period:</p>
<ul>
<li>Second quarter of 2012 GDP report downgraded real growth to 1.3%: the economy itself was on a downward trajectory.</li>
<li>Consumer spending stalled since August 2012.</li>
<li>Third opioid overdose wave started in 2013. The rise of <strong>illicitly manufactured fentanyl</strong> resulted in exponential increase in overdose death involving synthetic opioids.</li>
</ul>
<p>Regarding the last bulletpoint above, fentanyl has become one of the deadliest and widely used opioids in the United States today, as well as across the world. According to Centers for Disease Control and Prevention (CDC), it is a synthetic opioid that is <strong>50 times stronger than heroin and 100 times stronger than morphine.</strong> It is a major contributor to fatal and nonfatal overdoses in the U.S.</p>
<p><br>This synthetic opioid is so harzardous that being exposed to it just for a short period of time will make people experience severe sideeffects, ranging from sedation, confusion, drowsiness, dizziness, nausea and vomiting, urinary retention, pupillary constriction to respiratory depression. Fentanyl, along with other synthetic opioids, kills over 150 people die every day from overdoses. This is also due to it being a cheaper option as it takes very little to produce fentanyl. More information can be found here:</p>
<p>https://www.cdc.gov/stopoverdose/fentanyl/index.html https://www.forbes.com/sites/charleskadlec/2012/10/01/the-growth-recession-of-2012-and-the-presidential-election/?sh=176cb14447af</p>
</section>
<section id="synthetic-opioid-highest-overdose-death-rate-for-all-groups" class="level4">
<h4 class="anchored" data-anchor-id="synthetic-opioid-highest-overdose-death-rate-for-all-groups">2. Synthetic Opioid: Highest Overdose Death Rate for ALL GROUPS</h4>
<p>For all groups, both by sex and race, synthetic opioid showed the highest growth rate of overdose. This is mainly due to the rise of illicitly manufactured fentanyl use, which is described in detail above.</p>
</section>
</section>
<section id="significance-of-this-project" class="level3">
<h3 class="anchored" data-anchor-id="significance-of-this-project">Significance of This Project</h3>
<p>Throughout the project, I learned tremendously about how severely the opioid epidemic has affected the lives of people in a wide range of population. While there are other websites and sources that display the overall trend of opioid overdose, my analysis can function as an implication of which sex and/or race group showcases the greatest vulnerability to opioid addiction and overdose. This can also create more effective advocacy efforts by targeting specific high risk groups.</p>
</section>
<section id="limitations-potential-future-improvement" class="level3">
<h3 class="anchored" data-anchor-id="limitations-potential-future-improvement">Limitations &amp; Potential Future Improvement</h3>
<p>While I did my very best to provide in-depth analysis of the opioid overdose crisis, it is important to acknowledge some limitations: - Data of Asian or Pacific Islander and American Indian or Alaska Native were either missing completely or insufficient, which might have affected the validity of the result. - Despite hispanic being an ethnicity, I treated it as a race category. Since ethnicity is a much broader term than race, this might have decreased the accuracy and reliability of the analysis while miscalculating the scope of the population. - It is unclear how each race category is defined as. What about mixed race? - More statistical tests can be done to support my argument and findings.</p>
<p>In order to improve the overall validity of the project, I can undertake some tasks mentioned below: - Try to find a better datafile with more comprehensive data for both sex and race. Ideally, this should also address how the data was obtained, with what method and under what definition. - Calculate more statistical tests such as a goodness-of-fit by looking at R-squared score to see how well my predicted values match the actual value in the datafile.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>From 1999 to to 2019, the opioid overdose death rate significantly increased, especially among <strong><em>white males</em></strong> in the United States. Starting 2013, the rapid rise of synthetic opioid along with the existing opioids such as prescription opioids, cocaine and heroin accelerated the rate of addiction and overdose. While more research should be done to acquire more data points for American Indian or Alaska Native and Asian or Pacific Islander groups, it is apparent that opioid overdose has become one of the leading causes of death in the United States.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>